- name: Install snapd
  dnf:
    name: snapd
    state: latest
    update_cache: yes
  notify: Reload Logrotate

- name: Start snapd sockets
  service:
    name: snapd.socket
    enabled: true
    state: started

- name: Enabled snapd classic
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Ensure certbot-auto is removed
  file:
    path: /bin/certbot-auto
    state: absent

- name: Ensure certbot is uninstalled
  dnf:
    name: certbot
    state: absent

- name: Reboot to ensure snapd is properly seeded
  reboot:
    msg: "Reboot initiated by Ansible"

- name: Ensure snap is up-to-date
  command: "snap install core"

- name: Ensure snap is refreshed
  command: "snap refresh core"

- name: Install certbot
  command: "snap install --classic certbot"

- name: Enabled snapd classic
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

- name: Set up certificates
  command: "certbot --nginx -n -d {{ domains | join(' -d ') }}"