- name: Install snapd
  dnf:
    name: snapd
    state: latest
    update_cache: yes

- name: Start snapd sockets
  service:
    name: snapd.socket
    enabled: true
    state: started

- name: Enabled snapd classic
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link

- name: Reboot to ensure snapd is properly seeded
  reboot:

- name: Ensure certbot-auto is removed
  file:
    path: /bin/certbot-auto
    state: absent

- name: Ensure certbot is uninstalled
  dnf:
    name: certbot
    state: absent

- name: Ensure snap is up-to-date
  command: "snap install core; sudo snap refresh core"

- name: Install certbot
  command: "snap install --classic certbot"

- name: Enabled snapd classic
  file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link
