---
- hosts: os_metadata_my_server_role=jenkins
  become: true

  vars_files:
    - ../terraform/tf_ansible_vars.yaml
    - private.yaml
    - paths.yaml

  vars:
    # Security
    sftp_enabled: true
    security_sudoers_passwordless:
      - centos

    # Domains
    jenkins_endpoint: "{{ inventory_hostname + '.' + zone_name }}"

    # Jenkins
    jenkins_http_port: 8080
    jenkins_hostname: localhost
    jenkins_ip: 127.0.0.1
    jenkins_local: "{{ jenkins_hostname + ':' + jenkins_http_port|string }}"
    jenkins_ip_addr: "{{ jenkins_ip + ':' + jenkins_http_port|string }}"
    jenkins_package_state: latest
    jenkins_plugins_state: latest
    jenkins_home: /storage/jenkins
    java_packages:
      - java-1.8.0-openjdk

    # .Net Core
    dotnet_package: "dotnet-sdk-3.1"
    
    # Certbot/Let's Encrypt
    certbot_install_from_source: false
    certbot_pkg_mgr: dnf
    certbot_admin_email: "{{ letsencrypt_email }}"
    certbot_create_if_missing: true
    certbot_certs:
      - domains:
        - "{{ jenkins_endpoint }}"


  pre_tasks:
    - name: Ensure Terraform variables have been imported
      assert:
        that:
          - zone_name is defined

    - name: Ensure path variables have been imported
      assert:
        that:
          - private_cert_path is defined

    - name: Ensure private variables have been imported
      assert:
        that:
          - letsencrypt_email is defined

    - name: Add EPEL repository
      dnf:
        name: epel-release
        state: latest

    - name: Upgrade system
      dnf:
        name: "*"
        state: latest

    - name: Create a filesystem on /dev/sdb
      filesystem:
        fstype: ext4
        dev: /dev/sdb

    - name: Mount volume
      mount:
        path: /storage
        src: /dev/sdb
        fstype: ext4
        state: mounted

    - name: Copy host list
      copy:
        src: ../terraform/host_list
        dest: "{{ host_list_path }}"

    - name: Template web deployment
      template:
        src: templates/web_deploy.yaml.j2
        dest: /storage/web_deploy.yaml
        mode: 0755

    - name: Template api deployment
      template:
        src: templates/api_deploy.yaml.j2
        dest: /storage/api_deploy.yaml
        mode: 0755
    
    - name: Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        persistent: yes
        state: yes

    - name: Enable rsync_client
      seboolean:
        name: rsync_client
        persistent: yes
        state: yes

    - name: Enable rsync 
      seboolean:
        name: rsync_full_access
        persistent: yes
        state: yes

  roles:
    - role: geerlingguy.security
    - role: dev-sec.ssh-hardening
    - role: geerlingguy.git
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
    - role: ocha.yarn
    - role: certbot
  
  tasks:
    - name: Install .Net Core
      dnf:
        name: dotnet-sdk-3.1
        state: latest
    
    - name: Install Ansible
      dnf:
        name: ansible
        state: latest
    
    - name: Install Zip
      dnf:
        name: zip
        state: latest

    - name: Install Cypress Dependencies
      dnf:
        name: "{{ item }}"
        state: latest
      loop:
        - xorg-x11-server-Xvfb
        - gtk2-devel
        - gtk3-devel
        - libnotify-devel
        - GConf2
        - nss
        - libXScrnSaver
        - alsa-lib

    - name: Install Nginx
      dnf:
        name: nginx
        state: latest
    
    - name: Template Nginx config
      template:
        src: templates/jenkins.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx
        - Restart Nginx Amplify

    - name: Allow Nginx to read certificates
      file:
        path: /etc/letsencrypt/live
        state: directory
        recurse: yes
        group: nginx
        mode: 0750

    - name: Allow Nginx to read certificates
      file:
        path: /etc/letsencrypt/archive
        state: directory
        recurse: yes
        group: nginx
        mode: 0750

    - name: Allow Nginx to read own config
      file:
        path: /etc/nginx
        state: directory
        recurse: yes
        group: nginx

    - name: Start Nginx
      service:
        name: nginx
        enabled: true
        state: started

    - name: Create GPG directory
      file:
        path: /var/gpg
        state: directory
        recurse: yes
        mode: 0700
  
    - name: Copy gpg keys
      copy:
        src: gpg/lavinia.key
        dest: /var/gpg/lavinia.key
        mode:  0600

    - name: Make sure the GPG config exists
      command: "gpg --list-keys"
      args:
        creates: "~/.gnupg"

    - name: Import public key
      command: "gpg --import /var/gpg/lavinia.key"
      
    - name: Copy logrotate config
      template:
        src: templates/logrotate.conf.j2
        dest: /etc/logrotate.d/nginx
        mode: 0644
      notify: Reload Logrotate
    
    - name: Check if Service Exists
      stat: path=/etc/init.d/amplify-agent
      register: amplify_service

    - name: Add Nginx signing key
      rpm_key:
        key: http://nginx.org/keys/nginx_signing.key
      when: not amplify_service.stat.exists

    - name: Add Amplify repo
      yum_repository:
        description: nginx repo
        name: nginx-amplify
        baseurl: http://packages.amplify.nginx.com/centos/8/$basearch
        gpgcheck: yes
      when: not amplify_service.stat.exists

    - name: Install Nginx Amplify
      dnf:
        name: nginx-amplify-agent
        state: latest
        update_cache: yes
      when: not amplify_service.stat.exists

    - name: Copy config
      copy:
        remote_src: yes
        src: /etc/amplify-agent/agent.conf.default
        dest: /etc/amplify-agent/agent.conf
        mode: 0644
      when: not amplify_service.stat.exists

    - name: Insert API key
      replace:
        path: /etc/amplify-agent/agent.conf
        regexp: 'api_key.*$'
        replace: 'api_key = {{ amplify_key }}'
      when: not amplify_service.stat.exists
    
    - name: Copy stub_status
      copy:
        src: templates/stub_status.conf
        dest: /etc/nginx/conf.d/stub_status.conf
        mode: 0644
      when: not amplify_service.stat.exists
      notify:
        - Restart Nginx
        - Restart Nginx Amplify

    - name: Start Amplify agent
      service:
        name: amplify-agent
        enabled: true
        state: started
      when: not amplify_service.stat.exists
    
    - name: get service facts
      service_facts:

    - name: Open port 80
      firewalld:
        immediate: yes
        port: 80/tcp
        state: enabled
      when: ansible_facts.services["firewalld.service"].state == "started"

    - name: Open port 443
      firewalld:
        immediate: yes
        port: 443/tcp
        state: enabled
      when: ansible_facts.services["firewalld.service"].state == "started"

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart Nginx Amplify
      service:
        name: amplify-agent
        state: restarted

    - name: Reload Logrotate
      command:
        cmd: logrotate -v /etc/logrotate.conf