vars_files:
- jenkins.vars.yaml

nginx_http_template_enable: true
nginx_http_template:
  default:
    template_file: http/default.conf.j2
    conf_file_name: default.conf
    conf_file_location: /etc/nginx/conf.d/
    servers:
      app:
        template_file: http/default.conf.j2
        conf_file_name: default.conf
        conf_file_location: /etc/nginx/conf.d/
        servers:
          server1:
            listen:
              listen_localhost:
                ip: 0.0.0.0
                port: 80
                opts:
                  - default_server
            server_name: localhost
            http_error_pages:
              404: /404.html
            error_page: /usr/share/nginx/html
            client_max_body_size: 512k
            proxy_hide_headers:
              - X-Powered-By
            add_headers:
              strict_transport_security:
                name: Strict-Transport-Security
                value: max-age=15768000; includeSubDomains
                always: true
            sub_filter:
              # sub_filters: []
              last_modified: "off"
              once: "on"
              types: "text/html"
          server2:
            listen:
              listen_localhost:
                  ip: localhost  # Wrap in square brackets for IPv6 addresses
                  port: 443
                  ssl: true
                  opts: []  # Listen opts like http2 which will be added (ssl is automatically added if you specify 'ssl:').
            ssl:
              cert: /etc/letsencrypt/live/{{jenkins_endpoint}}/fullchain.pem
              key: /etc/letsencrypt/live/{{jenkins_endpoint}}/privkey.pem
            server_name: "{{jenkins_endpoint}}"
            error_page: /usr/share/nginx/html
            access_log:
            - name: main
              location: /var/log/nginx/access.log
            error_log:
              location: /var/log/nginx/error.log
              level: warn
            https_redirect: $host
            client_max_body_size: 1m
            
            reverse_proxy:
              locations:
                jenkins_server:
                  location: /
                  proxy_pass: http://jenkins
                  proxy_set_header:
                    header_host:
                      name: Host
                      value: $host
                    header_x_real_ip:
                      name: X-Real-IP
                      value: $remote_addr
                    header_x_forwarded_for:
                      name: X-Forwarded-For
                      value: $proxy_add_x_forwarded_for
                    header_x_forwarded_proto:
                      name: X-Forwarded-Proto
                      value: $scheme
                  proxy_read_timeout: 90s
                  proxy_buffering: false
                  proxy_http_version: 1.1
        upstreams:
          jenkins:
            name: jenkins
            lb_method: least_conn
            zone_name: backend_mem_zone
            zone_size: 64k
            sticky_cookie: false
            servers:
              server1:
                address: "{{jenkins_hostname}}"
                port: "{{jenkins_http_port}}"
                weight: 1
                health_check: fail_timeout=0