---
- hosts: os_metadata_my_server_role=web
  become: true

  vars_files:
    - ../terraform/tf_ansible_vars.yaml
    - private.yaml
    - paths.yaml

  vars:
    # Repository
    client_repo: Project-Lavinia/Lavinia-client

    # Web
    nginx_user: nginx

    # Security
    sftp_enabled: true
    security_sudoers_passwordless:
      - centos

    # Domains
    web_endpoint: "{{ inventory_hostname + '.' + zone_name }}"
    
    # Certbot/Let's Encrypt
    domains:
      - "{{ web_endpoint }}"


  pre_tasks:
    - name: Ensure Terraform variables have been imported
      assert:
        that:
          - zone_name is defined

    - name: Ensure path variables have been imported
      assert:
        that:
          - web_root is defined

    - name: Ensure private variables have been imported
      assert:
        that:
          - letsencrypt_email is defined

    - name: Add EPEL repository
      dnf:
        name: epel-release
        state: latest

    - name: Upgrade system
      dnf:
        name: "*"
        state: latest
    
    - name: Create web root
      file:
        name: "{{ web_root }}"
        owner: centos
        mode: 0755
        state: directory
        recurse: yes

    - name: Add additional SSH keys
      authorized_key:
        user: centos
        state: present
        key: "{{ lookup('file', '~/.ssh/jenkins/id_rsa.pub') }}"
    
    - name: Allow Nginx to serve web root
      command: chcon -R -t httpd_sys_content_t "{{ web_root }}"
  
    - name: Enable httpd_can_network_connect
      seboolean:
        name: httpd_can_network_connect
        persistent: yes
        state: yes

  roles:
    - role: geerlingguy.security
    - role: dev-sec.ssh-hardening
    - role: geerlingguy.git
  
  tasks:
    - name: get service facts
      service_facts:

    - name: Open port 80
      firewalld:
        immediate: yes
        permanent: yes
        port: 80/tcp
        state: enabled
      when: ansible_facts.services["firewalld.service"].state == "running"

    - name: Open port 443
      firewalld:
        immediate: yes
        permanent: yes
        port: 443/tcp
        state: enabled
      when: ansible_facts.services["firewalld.service"].state == "running"

    - name: Install unzip
      dnf:
        name: unzip
        state: latest

    - name: Check if web root is empty
      find:
        paths: "{{ web_root }}/"
      register: filesFound
    
    - name: Get latest release link
      when: filesFound.matched == 0
      shell: 'curl -s https://api.github.com/repos/{{ client_repo }}/releases/latest \
                | grep "browser_download_url.*zip" \
                | cut -d : -f 2,3 \
                | tr -d \"'
      register: releaseUrl

    - name: Download latest release
      when: filesFound.matched == 0
      unarchive:
        remote_src: yes
        src: "{{ releaseUrl.stdout }}"
        dest: "{{ web_root }}/"

    - name: Install Nginx
      dnf:
        name: nginx
        state: latest
    
    - name: Template Nginx config
      template:
        src: templates/web.conf.j2
        dest: /etc/nginx/nginx.conf
      notify:
        - Restart Nginx
        - Restart Nginx Amplify
    
    - name: Harden Nginx
      include_role:
        name: dev-sec.nginx-hardening
  
    - name: Force custom Content Security Policy
      lineinfile:
        path: /etc/nginx/conf.d/90.hardening.conf
        state: absent
        regexp: 'Content-Security-Policy'

    - include_tasks: certbot.yaml

    - name: Allow Nginx to read certificates
      file:
        path: /etc/letsencrypt/live
        state: directory
        recurse: yes
        group: nginx
        mode: 0750

    - name: Allow Nginx to read certificates
      file:
        path: /etc/letsencrypt/archive
        state: directory
        recurse: yes
        group: nginx
        mode: 0750

    - name: Allow Nginx to read own config
      file:
        path: /etc/nginx
        state: directory
        recurse: yes
        group: nginx
    
    - name: Start Nginx
      service:
        name: nginx
        enabled: true
        state: started

    - name: Execute logrotate hourly
      copy:
        src: /etc/cron.daily/logrotate
        dest: /etc/cron.hourly/
        remote_src: yes
        mode: 0755

    - name: Create GPG directory
      file:
        path: /var/gpg
        state: directory
        recurse: yes
        mode: 0700
  
    - name: Copy gpg keys
      copy:
        src: gpg/lavinia.key
        dest: /var/gpg/lavinia.key
        mode:  0600

    - name: Make sure the GPG config exists
      command: "gpg --list-keys"
      args:
        creates: "~/.gnupg"

    - name: Import public key
      command: "gpg --import /var/gpg/lavinia.key"
      
    - name: Copy logrotate config
      template:
        src: templates/logrotate.conf.j2
        dest: /etc/logrotate.d/nginx
        mode: 0644
      notify: Reload Logrotate
  
    - name: Check if Service Exists
      stat: path=/etc/init.d/amplify-agent
      register: amplify_service

    - name: Add Nginx signing key
      rpm_key:
        key: http://nginx.org/keys/nginx_signing.key
      when: not amplify_service.stat.exists

    - name: Add Amplify repo
      yum_repository:
        description: nginx repo
        name: nginx-amplify
        baseurl: http://packages.amplify.nginx.com/centos/8/$basearch
        gpgcheck: yes
      when: not amplify_service.stat.exists

    - name: Install Nginx Amplify
      dnf:
        name: nginx-amplify-agent
        state: latest
        update_cache: yes
      when: not amplify_service.stat.exists

    - name: Copy config
      copy:
        remote_src: yes
        src: /etc/amplify-agent/agent.conf.default
        dest: /etc/amplify-agent/agent.conf
        mode: 0644
      when: not amplify_service.stat.exists

    - name: Insert API key
      replace:
        path: /etc/amplify-agent/agent.conf
        regexp: 'api_key.*$'
        replace: 'api_key = {{ amplify_key }}'
      when: not amplify_service.stat.exists
    
    - name: Copy stub_status
      copy:
        src: templates/stub_status.conf
        dest: /etc/nginx/conf.d/stub_status.conf
        mode: 0755
      when: not amplify_service.stat.exists
      notify:
        - Restart Nginx
        - Restart Nginx Amplify

    - name: Start Amplify agent
      service:
        name: amplify-agent
        enabled: true
        state: started
      when: not amplify_service.stat.exists

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted

    - name: Restart Nginx Amplify
      service:
        name: amplify-agent
        state: restarted

    - name: Reload Logrotate
      command:
        cmd: logrotate -v /etc/logrotate.conf